package models;
// Generated Nov 13, 2017 1:54:06 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Donaciones generated by hbm2java
 */
public class Donaciones  implements java.io.Serializable {


     private Integer idDonacion;
     private int idDonador;
     private int idBeneficiado;
     private Date horaDonacion;
     private int idProducto;

    public Donaciones() {
    }

    public Donaciones(int idDonador, int idBeneficiado, Date horaDonacion, int idProducto) {
       this.idDonador = idDonador;
       this.idBeneficiado = idBeneficiado;
       this.horaDonacion = horaDonacion;
       this.idProducto = idProducto;
    }
   
    public Integer getIdDonacion() {
        return this.idDonacion;
    }
    
    public void setIdDonacion(Integer idDonacion) {
        this.idDonacion = idDonacion;
    }
    public int getIdDonador() {
        return this.idDonador;
    }
    
    public void setIdDonador(int idDonador) {
        this.idDonador = idDonador;
    }
    public int getIdBeneficiado() {
        return this.idBeneficiado;
    }
    
    public void setIdBeneficiado(int idBeneficiado) {
        this.idBeneficiado = idBeneficiado;
    }
    public Date getHoraDonacion() {
        return this.horaDonacion;
    }
    
    public void setHoraDonacion(Date horaDonacion) {
        this.horaDonacion = horaDonacion;
    }
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }




}


