package models;
// Generated Nov 13, 2017 1:54:06 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ProductosBloqueados generated by hbm2java
 */
public class ProductosBloqueados  implements java.io.Serializable {


     private Integer idBloqueo;
     private int idProducto;
     private int idUsuario;
     private String descripcionBloqueo;
     private Date fechaBloqueo;

    public ProductosBloqueados() {
    }

    public ProductosBloqueados(int idProducto, int idUsuario, String descripcionBloqueo, Date fechaBloqueo) {
       this.idProducto = idProducto;
       this.idUsuario = idUsuario;
       this.descripcionBloqueo = descripcionBloqueo;
       this.fechaBloqueo = fechaBloqueo;
    }
   
    public Integer getIdBloqueo() {
        return this.idBloqueo;
    }
    
    public void setIdBloqueo(Integer idBloqueo) {
        this.idBloqueo = idBloqueo;
    }
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getDescripcionBloqueo() {
        return this.descripcionBloqueo;
    }
    
    public void setDescripcionBloqueo(String descripcionBloqueo) {
        this.descripcionBloqueo = descripcionBloqueo;
    }
    public Date getFechaBloqueo() {
        return this.fechaBloqueo;
    }
    
    public void setFechaBloqueo(Date fechaBloqueo) {
        this.fechaBloqueo = fechaBloqueo;
    }




}


