package models;
// Generated Nov 13, 2017 1:54:06 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ProductoPedido generated by hbm2java
 */
public class ProductoPedido  implements java.io.Serializable {


     private Integer idPedido;
     private int idDonante;
     private int idSolicitante;
     private boolean ganador;
     private Date fechaPedido;
     private int idProducto;

    public ProductoPedido() {
    }

    public ProductoPedido(int idDonante, int idSolicitante, boolean ganador, Date fechaPedido, int idProducto) {
       this.idDonante = idDonante;
       this.idSolicitante = idSolicitante;
       this.ganador = ganador;
       this.fechaPedido = fechaPedido;
       this.idProducto = idProducto;
    }
   
    public Integer getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(Integer idPedido) {
        this.idPedido = idPedido;
    }
    public int getIdDonante() {
        return this.idDonante;
    }
    
    public void setIdDonante(int idDonante) {
        this.idDonante = idDonante;
    }
    public int getIdSolicitante() {
        return this.idSolicitante;
    }
    
    public void setIdSolicitante(int idSolicitante) {
        this.idSolicitante = idSolicitante;
    }
    public boolean isGanador() {
        return this.ganador;
    }
    
    public void setGanador(boolean ganador) {
        this.ganador = ganador;
    }
    public Date getFechaPedido() {
        return this.fechaPedido;
    }
    
    public void setFechaPedido(Date fechaPedido) {
        this.fechaPedido = fechaPedido;
    }
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }




}


