package models;
// Generated Nov 13, 2017 1:54:06 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String descripcion;
     private byte[] indiceimagen;
     private boolean bloqueada;
     private Date fechaUpdateProducto;
     private String usuarioOfertor;

    public Productos() {
    }

    public Productos(String nombre, String descripcion, byte[] indiceimagen, boolean bloqueada, Date fechaUpdateProducto, String usuarioOfertor) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.indiceimagen = indiceimagen;
       this.bloqueada = bloqueada;
       this.fechaUpdateProducto = fechaUpdateProducto;
       this.usuarioOfertor = usuarioOfertor;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public byte[] getIndiceimagen() {
        return this.indiceimagen;
    }
    
    public void setIndiceimagen(byte[] indiceimagen) {
        this.indiceimagen = indiceimagen;
    }
    public boolean isBloqueada() {
        return this.bloqueada;
    }
    
    public void setBloqueada(boolean bloqueada) {
        this.bloqueada = bloqueada;
    }
    public Date getFechaUpdateProducto() {
        return this.fechaUpdateProducto;
    }
    
    public void setFechaUpdateProducto(Date fechaUpdateProducto) {
        this.fechaUpdateProducto = fechaUpdateProducto;
    }
    public String getUsuarioOfertor() {
        return this.usuarioOfertor;
    }
    
    public void setUsuarioOfertor(String usuarioOfertor) {
        this.usuarioOfertor = usuarioOfertor;
    }




}


